server:
  port: 9090
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql:///mydb
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    tomcat:
      max-idle: 100
      min-idle: 10
      max-active: 100
      max-wait: 10000
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
mybatis:
  type-aliases-package: java.util
  mapper-locations: mapper/*Mapper.xml


